### ISSUE TITLE
Changing the units of returned values

### ISSUE THREAD

**Issue by MarnoGrewar** [Ex-Mente/auxi.0#112]
### Background

During the use of  H, S and G functions thermochemistry module, it was found that if one can change the units of the return values, for example from kWh to Joules (J), would be helpful.
### Purpose

This change to auxi's returned values would enable users to choose the units the return value of a function must be displayed in. 
### Approach

A possible approach is to provide a list generally used units for a specific functions. Another approach is to provide a unit converter function or package to aid in converting return values from functions to required units. Any other suggestions to approach this issue will be greatly appreciated.

**Comment by johanzietsman-em** [comment]
Thanks for suggesting this Marno. It is an important aspect to address, and it would have a very wide impact within `auxi`.

I changed the purpose statement to be more clear.

**Comment by MarnoGrewar** [comment]
Johan thank for your feedback on my issue, and sorry for taking so long to respond. I edited my previous approach to be more clearly stated.

**Comment by johanzietsman-em** [comment]
Thanks Marno. My suggestion would be that we add another package/module to address the dimension and unit infrastructure required in `auxi`. Here are a few suggestions that have come to mind so far:

* Add a new `units.py` module into the `auxi.tools` package. I don't see that units will require a package of its own. A module should be sufficient.
* Introduce the concept of __dimensions__, and create the seven fundamental dimensions used for the base units in the SI system. These include length, mass, time, electric current, thermodynamic temperature, amount of substance and luminous intensity. (This should address most derived dimensions, but we may have to add something to address angles and money later on.)
* Create derived dimensions based on the fundamental dimensions, for example, mass flow rate, energy, power, velocity, etc.
* Introduce the concept of __units__ for dimensions, and create the seven base units used by the SI system for its seven fundamental dimensions.
* Create units for the derived dimensions by using the base units.

I don't think we should build units directly into all `auxi` calculations, since this will impair computational performance. We should do this as simply as possible through multiplication factors for unit conversions, and allowing users to ask `auxi` which units it is using for a specific calculation. I am not certain how we should do this yet, but the following concepts may become part of the implementation:

* __units set__: A module like `auxi.tools.chemistry.thermochemistry` may have its own units set to specify in which units it should perform its calculations. Users can select different units into this unit set, or change to a different units set altogether, to modify the units used.
* __dimension and units repository_: This repository should reside in the `units` module. It should list all the available dimensions, and all the available units for each dimension. Users can then select from the repository into units sets.

Some more thinking is required, but this is a start. I am moving this issue to Ready status so that we can start tinkering with the ideas. I will create branches for you and me to work on.

**Comment by johanzietsman-em** [comment]
Here are some projects that already address the units issue:
* [units](https://pypi.python.org/pypi/units)
* [numericalunits](https://pypi.python.org/pypi/numericalunits)
* [Pint](https://pint.readthedocs.io/en/0.7.2/)
* [quantities](https://pypi.python.org/pypi/quantities/)
* [Unum](http://home.scarlet.be/be052320/Unum.html)
* [PhysicalQuantities](http://dirac.cnrs-orleans.fr/ScientificPython/ScientificPythonManual/Scientific.Physics.PhysicalQuantities-module.html)
* [SimTK](https://simtk.org/projects/python_units)
* [Buckingham](https://github.com/mdipierro/buckingham)
* [Brian](http://briansimulator.org/)
* [natu](https://github.com/kdavies4/natu)
* [Sympy](http://docs.sympy.org/dev/modules/physics/units.html)

These are in the C++ world:
* [Boost.Units](http://www.boost.org/doc/libs/1_41_0/doc/html/boost_units.html)

A good start would be to see the principles behind what these guys have done. We should also create a bit of a requirement specification for our implementation. Since `auxi` is a scientific and engineering tool, units of measure are fundamental to what we do. It should integrate well with the entire framework, especially the modelling and simulation parts.
