### ISSUE TITLE
Rename phases in auxi.0\src\tools\chemistry\data\nist\Compound_Fe.json

### ISSUE THREAD

**Issue by SShilo** [Ex-Mente/auxi.0#155]
### Background

When compounds are listed using the `list_compounds` function and the 'Compound_Fe.json' five phases of iron are displayed. Three of these phases are named as follows: Fe[S1 (alp â delt)]. This appears to be incorrect.
### Purpose

The purpose of this issue is to rename the phases in this file to be clear to the user.

**Comment by alchemyst** [comment]
The phases in the file are actually listed as "S4 (alp \xe2\x80\x93 delt)", with the "\xe2\x80\x93" part being the UTF-8 sequence for an en dash. So it's actually "S4 (alp – delt)".

This problem is therefore not in the file, but whatever program you are using to view the output. It is not correctly displaying UTF-8 characters.
